In [1]:
import numpy as np


In [21]:
A=np.array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
v=np.array([-4,3,9,7],float)
N=len(v)
for i in range(N):
    div=A[i][i]
    A[i]/=div
    v[i]/=div
    for j in range(i+1,N):
        mult=A[j][i]
        A[j]-=mult*A[i]
        v[j]-=mult*v[i]
soln=np.empty(N,float)
for m in range(N-1,-1,-1):
    soln[m]=v[m]
    for i in range(m+1,N):
        soln[m]-=A[m,i]*soln[i]
    
print(soln)

[ 2. -1. -2.  1.]


# Exercise 6.1

## Without Pivoting

In [17]:

A=np.array([[4,-1,-1,-1],[-1,3,0,-1],[-1,-1,-1,4],[-1,0,3,-1]],float)
v=np.array([5,0,0,5],float)
N=len(v)
for i in range(N):
    div=A[i][i]
    A[i]/=div
    v[i]/=div
    for j in range(i+1,N):
        mult=A[j][i]
        A[j]-=mult*A[i]
        v[j]-=mult*v[i]
soln=np.empty(N,float)
for m in range(N-1,-1,-1):
    soln[m]=v[m]
    for i in range(m+1,N):
        soln[m]-=A[m,i]*soln[i]
    
print(soln)
A

[3.         1.66666667 3.33333333 2.        ]


array([[ 1.        , -0.25      , -0.25      , -0.25      ],
       [ 0.        ,  1.        , -0.09090909, -0.45454545],
       [-0.        , -0.        ,  1.        , -2.33333333],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## With Pivoting

In [18]:
A=np.array([[4,-1,-1,-1],[-1,0,3,-1],[-1,3,0,-1],[-1,-1,-1,4]],float)
v=np.array([5,5,0,0],float)
N=len(v)
for i in range(N):
    
            
    div=A[i][i]
    k=i
    while div==0:
        k+=1
        div=A[k+1][k]
    A[[i,k]]=A[[k,i]] 
    v[[i,k]]=v[[k,i]]
    
        
        
    div=A[i][i]    
    A[i]/=div
    v[i]/=div
    for j in range(i+1,N):
        mult=A[j][i]
        A[j]-=mult*A[i]
        v[j]-=mult*v[i]
soln=np.empty(N,float)
for m in range(N-1,-1,-1):
    soln[m]=v[m]
    for i in range(m+1,N):
        soln[m]-=A[m,i]*soln[i]
    
print(soln)

[3.         1.66666667 3.33333333 2.        ]


In [22]:
A=np.array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
v=np.array([-4,3,9,7],float)
N=len(v)
for i in range(N):
    
            
    div=A[i][i]
    k=i
    while div==0:
        k+=1
        div=A[k+1][k]
    A[[i,k]]=A[[k,i]] 
    v[[i,k]]=v[[k,i]]
    
        
        
    div=A[i][i]    
    A[i]/=div
    v[i]/=div
    for j in range(i+1,N):
        mult=A[j][i]
        A[j]-=mult*A[i]
        v[j]-=mult*v[i]
soln=np.empty(N,float)
for m in range(N-1,-1,-1):
    soln[m]=v[m]
    for i in range(m+1,N):
        soln[m]-=A[m,i]*soln[i]
    
print(soln)

[ 2. -1. -2.  1.]


In [2]:
A=np.array([[4,-1,-1,-1],[-1,3,0,-1],[-1,-1,-1,4],[-1,0,3,-1]],float)
v=np.array([5,0,0,5],float)

In [6]:
x=np.linalg.solve(A,v)
x

array([3.        , 1.66666667, 3.33333333, 2.        ])